### ISSUE TITLE
Missing one point in the output when no points should be clipped

### ISSUE THREAD

**Issue by claudijo** [Alamot/code-snippets#7]
Thanks for a great tutorial and code snippets about Sutherland Hodgman clipping in 3D.

I've ported your `SutherlandHodgman` function to Rust. I might be missing something (perhaps c++ specific) but it seems clipping a polygon consisting of for instance 4 points, where no points should be clipped, will actually return only 3 points.

That is, if the check https://github.com/Alamot/code-snippets/blob/cf043e24f6e3ff44205ff4e9042a7d7ea96f7e95/graphics/SutherlandHodgman/Linux/SutherlandHodgman.cpp#L205   is "truthy" for all points, only 3 will be included in the output since the enclosing for loop only iterates over `i` from 0 to 2 https://github.com/Alamot/code-snippets/blob/cf043e24f6e3ff44205ff4e9042a7d7ea96f7e95/graphics/SutherlandHodgman/Linux/SutherlandHodgman.cpp#L202

To fix this, one could iterate over `i = 0; i < points.size(); i++` and  index the first point as is `points[i]` but change the index to access the next point from `points[i + 1]` to `points[(i + 1) % 4]` to wrap around.

Did I miss something or is this an issue with the current implementation?

**Comment by Alamot** [comment]
Can you provide an example case (input/output)?

**Comment by claudijo** [comment]
I assumed the following pseudo code would trigger the problem. Basically have four vertices on the non-clipping side of the plane.

starting_polygon = [(1, 1, 0), (1, 2, 0), (2, 2), (2, 1)]
clipping_plane = { normal: (-1, 0, 0, distance: 10 } // The normal might be need to be (1, 0, 0) instad, not sure

Expected to get 4 points back, since none should be clipped/removed, but only get 3. 

But when looking at you code again it seems like you duplicate the first point when adding it to an empty polygon, to mitigate the issue I describe. I initially overlooked this quirk with the polygon class and only focused on the actual clipping function. Sorry about that. 

I will close this issue.
